# Generated by Django 5.1.4 on 2024-12-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileanalyzer', '0002_finderobject_height_finderobject_pages_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finderobject',
            name='file_type',
            field=models.CharField(choices=[('I', 'Image'), ('T', 'Text'), ('V', 'Video'), ('A', 'Audio'), ('Z', 'Archive'), ('E', 'Executable'), ('S', 'Script'), ('W', 'Web'), ('D', 'Data'), ('U', 'Unknown')], default=None, max_length=2, null=True),
        ),
    ]
